### ISSUE TITLE
App doesn't detect actual power drain, shows 0.0W

### ISSUE THREAD

**Issue by Pokemetti** [dubrowgn/wattz#5] opened 2022-09-17 11:11 UTC
The app doesn't work properly on my Samsung Galaxy A52s 5G (Android 12, OneUI 4) and just shows an amperage and wattage of 0.0 all the time. I suspect it has something to do with a Samsung quirk, that gives milliampere instead of microampere. One way to solve this might be to check whether the suspected "milliampere" (probably ampere on Samsung phones) are actually bigger than, for example, 5"mA" and to not divide by 1000 again if that isn't the case (I have yet to see a phone that uses 20W or  20mW).
Then again, I'm not 100% sure whether this _is_ a Samsung quirk, but the logs show nothing suspicious.

**Comment by Anonymous2716** [comment] 2022-09-17 16:55
@Pokemetti  you can use this > https://github.com/Anonymous2716/Amp/releases 

to view that. For temporary use. Not sure if it will work. 

Source https://github.com/Anonymous2716/Amp/

**Comment by Pokemetti** [comment] 2022-09-17 17:08
What is that supposed to be? The apk doesn't even install.

**Comment by Anonymous2716** [comment] 2022-09-17 17:23
@Pokemetti okay.  I added the screenshots . check the app-2.apk . if it doesn't work then it won't.

**Comment by Pokemetti** [comment] 2022-09-17 17:27
What I'm asking you to do is to add one small conditionto the app, that apk is a totally different app with like no size at all (3.6kB classes.dex).

**Comment by Anonymous2716** [comment] 2022-09-17 17:31
@Pokemetti  Yeah you can check the java code.its small.works on mg phone (android 9). Actually first time wrote an app .can you please elaborate "condition"?

**Comment by PrototypeGR** [comment] 2022-09-17 17:46
On S22 Ultra it won't show the watts as well.

**Comment by Pokemetti** [comment] 2022-09-17 17:52
I opened a pull request for the changes, have no idea whether they work since I have never even looked at Kotlin, so this is only based on my knowledge in Python and C.

**Comment by dubrowgn** [comment] 2022-09-17 21:58
Thanks for the issue report and input, everyone. A friend of mine has an S10. I'll see if I can reproduce it there, probably tomorrow morning. If it's just reporting incorrect units, something like @Pokemetti's PR could work. A quick Google search seems to indicate Samsung may be reporting mA instead of uA, as specified by the API docs: https://forum.developer.samsung.com/t/charging-current-battery-property-current-now/13517/3. From that thread, it seems like `BATTERY_PROPERTY_CHARGE_COUNTER` (also used in this app) might also be affected.

**Comment by dubrowgn** [comment] 2022-09-17 22:06
Interestingly, https://github.com/home-assistant/android/issues/2846 seems to suggest that some devices also report current in nA as well...

**Comment by dubrowgn** [comment] 2022-09-18 12:49
So I reproduced the issue for battery current on an S10, but charge level looks correct. Is anyone here also seeing an incorrect value for charge level? It should be somewhere in the single digit Ah range.

**Comment by dubrowgn** [comment] 2022-09-18 13:17
I published a new release which should work around this issue by dynamically detecting battery current units here: https://github.com/dubrowgn/wattz/releases/tag/v1.5. I'm going to close this issue as resolved, but please let me know if you continue to experience any problems.

**Closed by dubrowgn** 2022-09-18 13:17 UTC

**Comment by PrototypeGR** [comment] 2022-09-18 13:41
![Screenshot_20220918-163830_Wattz](https://user-images.githubusercontent.com/14006475/190905251-b60c73c4-b5b1-46c0-afb0-714dc938b769.png)
 Wattage shows correctly but the app reports the battery is full while it's not

**Comment by dubrowgn** [comment] 2022-09-18 13:55
@PrototypeGR I can reproduce that as well on the S10 I have, and it seems like yet another Samsung bug. Instead of returning `-1` to indicate "no value" as in the spec, it's returning `0`. I should be able to work around it fairly easily though by checking if the device is charging first.

**Comment by dubrowgn** [comment] 2022-09-18 14:00
Actually, it looks like it's always reporting `false` for `isCharging` as well. Their `BatteryManager` implementation sure is a wreck...

**Comment by Pokemetti** [comment] 2022-09-18 14:03
Works fine on my device, thanks!

**Comment by PrototypeGR** [comment] 2022-09-18 17:49
![Screenshot_20220918-204813_Wattz](https://user-images.githubusercontent.com/14006475/190921326-b43d998c-f57a-4ecb-817d-a2fb39d0254d.png)
While charging

**Comment by dubrowgn** [comment] 2022-09-19 13:04
I have a pair of work arounds which should address the remaining two issues on Samsung devices, but I'm waiting on a device to test it. Hopefully, I'll have a new build up later today.

**Comment by dubrowgn** [comment] 2022-09-19 15:35
@PrototypeGR can you try v1.6? All three issues seem to be fixed on the S10 I have.

**Comment by Pokemetti** [comment] 2022-09-19 15:51
They are definitely fixed on my device thanks!

**Comment by PrototypeGR** [comment] 2022-09-19 16:33
It's semi fixed, but it shows minus on power and current. Needs a + symbol while charging.
![Screenshot_20220919-193151_Wattz](https://user-images.githubusercontent.com/14006475/191067414-6fd3d7d1-7fce-46b8-9ef7-88ace9c429f6.png)

**Comment by dubrowgn** [comment] 2022-09-19 18:19
The app reports power draw. A negative sign is intentional, and indicates negative power draw from the battery.

**Comment by PrototypeGR** [comment] 2022-09-19 18:26
But it shows negative sign while charging not on battery
