### ISSUE TITLE
Wireless charging and Wattz

### ISSUE THREAD

**Issue by Ahhh-Mad** [dubrowgn/wattz#47] opened 2024-08-27 23:50 UTC
App shows battery fully charged while on wireless charging 
![Screenshot_20240828_024935_Chrome](https://github.com/user-attachments/assets/36abfde2-7de7-43e5-abea-3ccfa044dd79)

**Comment by dubrowgn** [comment] 2024-08-30 16:37
This looks like a dupe of https://github.com/dubrowgn/wattz/issues/33

**Closed by dubrowgn** 2024-08-30 16:37 UTC
Labels: duplicate
